#!/usr/bin/env bash
# Check if the script is run without any arguments

if [ "$1" == "" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
# Ping the IP address 5 times
	ping -c 5 "$1"
fi
