#!/usr/bin/env bash
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	# Infinite loop displaying the phrase with a sleep of 2 seconds.
	echo "To infinity and beyond"
	sleep 2
done
