#!/usr/bin/env bash
# Use a while loop to read the /etc/passwd file line by line
while read -r line
do
    # Display the relevant information
    echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
