#!/usr/bin/env bash
# Use a while loop to iterate from 1 to 20
counter=1
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo -e "\n$counter bad luck from China"
            ;;
        9)
            echo -e "\n$counter bad luck from Japan"
            ;;
        17)
            echo -e "\n$counter bad luck from Italy"
            ;;
        *)
            echo -e "$counter"
            ;;
    esac

    ((counter++))

done
