#!/usr/bin/env bash
# Use a while loop to iterate through hours and minutes.
counter=0
while [ $counter -le 12 ]
do
	echo "Hour: $counter"

	j=1
	while [ $j -lt 60 ]
	do
		echo "$j"
		((j++))
	done
	((counter++))
done
